In [1]:
print ('Hello world')

Hello world


In [12]:
import random
liste2 = [12,21,35,52]
liste1 = [random.randint(10,60) for i in range(20)]
print(liste1)
moyenneListe1 = sum(liste1)/len(liste1)
print(moyenneListe1)

[33, 33, 22, 40, 47, 55, 37, 17, 38, 33, 15, 18, 54, 31, 55, 52, 33, 39, 34, 31]
35.85


In [14]:
import numpy as np
revenus = [1800, 1500, 2200, 3000, 2172]
np.mean(revenus)

2134.4

In [15]:
x = [-2, -1, 1, 2]
print("La valeur absolue: ", np.abs(x))
print("Exponentielle: ", np.exp(x))
print("Logarithme: ", np.log(np.abs(x)))

La valeur absolue:  [2 1 1 2]
Exponentielle:  [0.13533528 0.36787944 2.71828183 7.3890561 ]
Logarithme:  [0.69314718 0.         0.         0.69314718]


In [16]:
revenus_array = np.array(revenus)
revenus_array
# array([1800, 1500, 2200, 3000, 2172])

array([1800, 1500, 2200, 3000, 2172])

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
# tableau représentant hugo, richard, émilie selon leur (age, salaire, nombre d'enfant)
hugo = [21, 1400, 0]
richard = [54, 2800, 2]
emilie = [27, 3700, 3]
tableau = [hugo, richard, emilie]