# Video 2 variables et fonctions

In [18]:
# f(x) = x^3
f = lambda x: x**3
print(f(5))

125


In [16]:
def e_potentielle(masse, hauteur, e_limite, g=9.81):
    E = masse*hauteur*g
    if E<e_limite :
        print ("L'énergie est de",E,'joules')
        return(E)
    else :
        print ("L'énergie à atteint sa limite, elle est donc de",e_limite,'joules')
        return(e_limite)

In [19]:
e_potentielle(100, 50, 40000)

L'énergie à atteint sa limite, elle est donc de 40000 joules


40000

# Video 3 PYTHON IF/ELSE, WHILE, FOR

In [46]:
sequence_nombre_pair = [i for i in range(10,100,2)]
for nombre_pair in sequence_nombre_pair:
    print (nombre_pair)

10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98


In [28]:
# generer une sequence de nombre dans une liste
sequence_nombre = [i for i in range(10,100,2)]
print (sequence_nombre)

[10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]


In [ ]:
1
1
2
3
5
8
13

In [11]:
def fibonacci1(n) :  
    n1=0
    n2=1
    for i in range(1000):
        suivant = n1 + n2
        if suivant < n:
            print(suivant)
        else : break
        n1=n2
        n2=suivant
 

In [12]:
fibonacci1(500)

1
2
3
5
8
13
21
34
55
89
144
233
377


In [ ]:
def fibonacci(n) :
    a=0
    b=1
    while a<n:
        print(a)
        a, b = b, a+b

In [10]:
fibonacci(10)

0
1
1
2
3
5
8


# Video 4 PYTHON LISTES et TUPLES

In [11]:
liste = ['Paris','Rome','Londres','Berlin']

In [12]:
len(liste)

4

In [14]:
liste.sort()
liste

['Berlin', 'Londres', 'Paris', 'Rome']

In [15]:
liste.sort(reverse=True)
liste

['Rome', 'Paris', 'Londres', 'Berlin']

In [16]:
liste.append('Paris')
liste

['Rome', 'Paris', 'Londres', 'Berlin', 'Paris']

In [17]:
liste.count('Paris')

2

In [20]:
liste.remove('Paris')

In [22]:
liste

['Rome', 'Londres', 'Berlin', 'Paris']

In [23]:
for index, valeur in enumerate(liste):
    print (index, valeur)

0 Rome
1 Londres
2 Berlin
3 Paris


In [26]:
liste2 = [i for i in range(5,10)]
liste2

[5, 6, 7, 8, 9]

In [27]:
for a,b in zip(liste2, liste):
    print (a,b)

5 Rome
6 Londres
7 Berlin
8 Paris


In [50]:
def fibonacci(n) :
    fibonacci_liste = []
    a=0
    b=1
    while a<n:
        fibonacci_liste.append(a)
        a, b = b, a+b
    return(fibonacci_liste)

In [51]:
fibonacci(100)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]

# Video 5 PYTHON DICTIONNAIRES

In [14]:
inventaire = {
    'bananes' : 5000,
    'pommes' : 2000,
    'cerises' : 3000,
    'melon' : 1000
}
inventaire

{'bananes': 5000, 'pommes': 2000, 'cerises': 3000, 'melon': 1000}

In [8]:
inventaire.values()

dict_values([5000, 2000, 3000, 1000])

In [35]:
inventaire.keys()

dict_keys(['bananes', 'pommes', 'cerises', 'melon'])

In [37]:
len(inventaire)

4

In [15]:
inventaire['pasteques']=500
inventaire

{'bananes': 5000,
 'pommes': 2000,
 'cerises': 3000,
 'melon': 1000,
 'pasteques': 500}

In [13]:
# créer un dictionnaire à partir de 2 listes 
legume = ['concombre','tomate','poivron']
quantite= [1200,1000,2000]

quantite_legume={legume : quantite for legume, quantite in zip(legume, quantite)}
quantite_legume

{'concombre': 1200, 'tomate': 1000, 'poivron': 2000}

In [43]:
ville = {}
ville.fromkeys(liste,'pas renseigné')

{'Rome': 'pas renseigné',
 'Londres': 'pas renseigné',
 'Berlin': 'pas renseigné',
 'Paris': 'pas renseigné'}

In [16]:
# retire l'association pasteque : 500 du dictionnaire mais enregistre 500 (la valeur) dans fruit
fruit = inventaire.pop('pasteques')
print (fruit)
inventaire

500


{'bananes': 5000, 'pommes': 2000, 'cerises': 3000, 'melon': 1000}

In [18]:
for i in inventaire.keys():
    print (i)

bananes
pommes
cerises
melon


In [48]:
for i in inventaire.values() :
    print (i)

5000
2000
3000
1000


In [49]:
for i,j in inventaire.items() :
    print (i,j)

bananes 5000
pommes 2000
cerises 3000
melon 1000


In [38]:
# Correction
classeur = {
        "positif" : [],
        "negatif" : []
    }
def trier(classeur, nombre):    
    if nombre > 0 :
        classeur["positif"].append(nombre)
    elif nombre == 0 : 
        print ("Le nombre est nul, pas d'intégration au classeur")
    else : 
        classeur["negatif"].append(nombre)
    return classeur

In [42]:
trier(classeur,-100)

{'positif': [8, 7, 9], 'negatif': [-100]}

# Video 6 PYTHON LIST DICT COMPREHENSION

In [27]:
liste1 = [i for i in range(4)]
liste1

[0, 1, 2, 3]

In [4]:
list3=[i**2 for i in range(10)]
list3

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [28]:
liste2 = [[i*j for i in range(4)] for j in range(3)]
liste2

[[0, 0, 0, 0], [0, 1, 2, 3], [0, 2, 4, 6]]

In [45]:
prenoms = ['Florian','Marie','Jean','Judith','Raphael']

In [46]:
dico_famille_1={k:v for k,v in enumerate(prenoms)}
dico_famille_1

{0: 'Florian', 1: 'Marie', 2: 'Jean', 3: 'Judith', 4: 'Raphael'}

In [30]:
dico = {k:v for k,v in enumerate(prenoms)}
dico

{0: 'Florian', 1: 'Marie', 2: 'Jean', 3: 'Judith', 4: 'Raphael'}

In [47]:
ages=[46,42,34,31,27]
dico2={ prenom:age for prenom,age in zip(prenoms,ages) if age>30}
dico2

{'Florian': 46, 'Marie': 42, 'Jean': 34, 'Judith': 31}

In [48]:
# permet de creer un dictionnaire avec 2 listes
dico_famille_2={prenom:age for prenom,age in zip(prenoms,ages)}
dico_famille_2

{'Florian': 46, 'Marie': 42, 'Jean': 34, 'Judith': 31, 'Raphael': 27}

In [32]:
tuple_1=tuple(i**2 for i in range (10))
tuple_1

(0, 1, 4, 9, 16, 25, 36, 49, 64, 81)

In [50]:
liste1=[k for k in range (20)]
liste1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [49]:
liste2=[k**2 for k in range(20)]
liste2

[0,
 1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361]

In [56]:
dico = {k : v for k,v in enumerate(v**2 for v in range(20)) }
dico

{0: 0,
 1: 1,
 2: 4,
 3: 9,
 4: 16,
 5: 25,
 6: 36,
 7: 49,
 8: 64,
 9: 81,
 10: 100,
 11: 121,
 12: 144,
 13: 169,
 14: 196,
 15: 225,
 16: 256,
 17: 289,
 18: 324,
 19: 361}

# Video 7 PYTHON BUILT-IN FUNCTIONS

In [64]:
list(dico)

In [61]:
# all renvoie False si un des élements = 0
# any renvoie True si au moins un des éléments n'est pas égale à 0
all(list3)
any(list3)

True

In [69]:
prenom = input('Entrez votre prénom',)

Entrez votre prénomjojo


In [76]:
heure = 14
date = '04/12/2022'
date=pd.to_datetime(date)
message = 'il est {}h et nous sommes le {}'.format(heure,date)
message

'il est 14h et nous sommes le 2022-04-12 00:00:00'

<built-in method date of Timestamp object at 0x000001DBC5165970>


In [81]:
import datetime as dt
heure = 14
date = '04/12/2022'
dt.date(date)
message = f'il est {heure}h et nous sommes le {date}'
message

TypeError: an integer is required (got type str)

In [67]:
# type set --> collection non ordonnée
set_list3=set(list3)
type(set_list3)

set

In [76]:
from datetime import datetime
datetime.now().time()

datetime.time(19, 51, 41, 544639)

## # Open

In [82]:
f = open('fichier.txt', 'w')

In [83]:
f.write('bonjour')
f.close()

In [84]:
f=open('fichier.txt', 'r')
print(f.read())
f.close()

bonjour


In [97]:
with open('fichier.txt', 'w') as f:
    for i in range(10):
        f.write("{}^2 = {} \n".format(i,i**2))

In [98]:
liste=[]
with open('fichier.txt', 'r') as f:
    liste.append(f.read().splitlines())
liste

[['0^2 = 0 ',
  '1^2 = 1 ',
  '2^2 = 4 ',
  '3^2 = 9 ',
  '4^2 = 16 ',
  '5^2 = 25 ',
  '6^2 = 36 ',
  '7^2 = 49 ',
  '8^2 = 64 ',
  '9^2 = 81 ']]

# Video 8 PYTHON MODULES ET PACKAGES

In [5]:
import numpy
import pandas

In [6]:
# package : paquet de modules

In [2]:
import math
import random
import statistics as st
import os
import glob

In [101]:
math.pi

3.141592653589793

In [103]:
# choici un element aleatoire dans la liste
random.choice(list3)

1

In [7]:
# l'aléatoire qui suit va toujours être le même
random.seed(0)
# choisi k elements dans la liste et les replace
random.choices(list3, k=3)

[64, 49, 16]

In [9]:
random.sample(list3, k=3)

[64, 49, 36]

In [135]:
# melange la liste
random.shuffle(list3)
list3

[81, 1, 36, 64, 25, 16, 0, 4, 49, 9]

In [158]:
random.sample(range(100), 20)

[42, 69, 26, 77, 70, 75, 36, 56, 11, 76, 49, 40, 73, 30, 37, 23, 24, 4, 78, 84]

In [156]:
# affiche une liste de 10 nombres aléatoires entre 0 et 100
print (random.sample(range(100),10))

[11, 10, 40, 65, 62, 13, 38, 70, 37, 90]


In [147]:
# affiche une liste de 0 à 10 nombres aléatoires entre 0 et 100
print (random.sample(range(100), random.randrange(10)))

[36, 17]


In [160]:
liste=[i for i in range (20)]
liste

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [163]:
random.shuffle(liste)
liste

[13, 1, 17, 4, 10, 12, 11, 6, 3, 16, 7, 14, 5, 18, 19, 0, 9, 15, 2, 8]

In [18]:
print (list(i for i in range(20)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [166]:
os.getcwd()

'C:\\Users\\Raphaël\\Fichiers Jupyter\\Videos_yt_machine_learnia'

In [167]:
print (glob.glob("*"))

['fichier.txt', 'Machine Learnia Bases.ipynb']


In [165]:
filesnames = glob.glob("*.txt")
d={}
for file in filesnames:
    with open(file, 'r') as f:
        d[file]=f.read().splitlines()
d  

{'fichier.txt': ['0^2 = 0 ',
  '1^2 = 1 ',
  '2^2 = 4 ',
  '3^2 = 9 ',
  '4^2 = 16 ',
  '5^2 = 25 ',
  '6^2 = 36 ',
  '7^2 = 49 ',
  '8^2 = 64 ',
  '9^2 = 81 ']}

# Video 10 PYTHON NUMPY machine learning

In [1]:
import numpy as np

In [34]:
array1 = np.arange(10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
type(array1)

numpy.ndarray

In [45]:
np.random.randint((2,3,4))

array([1, 1, 2])

In [46]:
array1.count(4)

AttributeError: 'numpy.ndarray' object has no attribute 'count'

In [70]:
np.ndarray((3,2), dtype=int)

array([[-1804644368,         550],
       [          0,           0],
       [          1,          46]])

In [74]:
array3 = np.ndarray((3,2), dtype=int)
array3

array([[-1804644368,         550],
       [          0,           0],
       [          1,     7667811]])

In [76]:
array3.argmax()

5

In [80]:
array3.cumsum(axis=0)

array([[-1804644368,         550],
       [-1804644368,         550],
       [-1804644367,     7668361]], dtype=int32)

In [87]:
array3.size

6

In [90]:
A = np.array([1,2,3])
A.shape

(3,)

In [94]:
np.random.seed(1)
np.random.randn(3,4)

array([[ 1.62434536, -0.61175641, -0.52817175, -1.07296862],
       [ 0.86540763, -2.3015387 ,  1.74481176, -0.7612069 ],
       [ 0.3190391 , -0.24937038,  1.46210794, -2.06014071]])

In [101]:
np.linspace(0,20,21)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20.])

In [102]:
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [3]:
array1=np.random.randn(3,3)

In [4]:
array1.shape

(3, 3)

In [8]:
A = np.zeros(3)
A

array([0., 0., 0.])

In [9]:
A.shape

(3,)

In [10]:
A.size

3

In [15]:
B = np.zeros((3,2,2,3))

In [16]:
B.ndim

4

In [17]:
B.shape

(3, 2, 2, 3)

In [18]:
B.size

36

In [24]:
np.random.seed(0)
np.random.randn(3,3)

array([[ 1.76405235,  0.40015721,  0.97873798],
       [ 2.2408932 ,  1.86755799, -0.97727788],
       [ 0.95008842, -0.15135721, -0.10321885]])

In [26]:
np.random.rand(3,3)

array([[0.87001215, 0.97861834, 0.79915856],
       [0.46147936, 0.78052918, 0.11827443],
       [0.63992102, 0.14335329, 0.94466892]])